# Generated by Django 3.2.3 on 2024-11-28 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_recipe_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart_recipe', to=settings.AUTH_USER_MODEL, verbose_name='владелец корзины покупок'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart_recipe', to='recipes.recipe', verbose_name='рецепт'),
        ),
    ]
